#  the code from chap 9 write you own methods

def say_moo
  puts "moooooo"
end
 say_moo
 say_moo

def say_moo number_of_moos
  puts "mooooooo.."*number_of_moos
end
say_moo 10
# say_moo  # this one throw and error because the argument for the number of moos param is missing

def double_this num
  num_times_2 = num * 2
  puts num.to_s + " doubled is " + num_times_2.to_s
end
double_this 44

tough_var = "You can't even touch my variable"

def little_pest tough_var
  tough_var = nil
  puts "HAHA, I ruined your variable!"
end
little_pest tough_var
puts tough_var

def say_moo number_of_moos
  puts "moooooooo..." * number_of_moos
  "yellow submarine"
end
puts say_moo 3  # if we add the puts it will also print the return val of methods
                #  which in this case is yellow submarine

x = say_moo 4
puts x.capitalize + ", dude...."  #  thess show the return value of x to be
puts x + "."                      #  yellow submarine

def favorite_food name
  if name == "Lister"
    return "vindaloo"
  end
  if name == "Rimmer"
    return "mashed potatoes"
  end
  "hard to say... maybe fried plantain?"
end

def favorite_drink name
  if name == "Jean-Luc"
    "tea, Earl Grey, hot"  # above we explicitely return person fav food
  elsif name == "Kate"     # here we are implicitly return persons fav food
    "coffee, black"        # the output generated by fav_drink code below looks
  else                     # exactly like code generated by fav_food code
    "perhaps... hot chocolate"
  end
end
puts favorite_food("Lister")
puts favorite_food("Rimmer")
puts favorite_food("Cher")
puts favorite_food("Bono")

puts favorite_drink("Jean-Luc")
puts favorite_drink("Kate")
puts favorite_drink("Oprah")

def ask question
  while true
    puts question
    reply = gets.chomp.downcase

    if (reply == "yes" || reply == "no")
      if reply == "yes"
        answer = true
      else
        answer = false
      end
      break
    else
      puts "Please answer yes or no."
    end
  end
  answer # This is what we return (true of false)
end      # it is the return value of wets_bed bed question
  puts "Hello, and thank you for . . . ."
  puts
  ask "Do you like eating tacos?" #Ignore this return value
  ask "Do you like eating burritos?" #And this one
  wets_bed = ask "Do you wet the bed?" # Save this return value
  ask "Do you like eating chimichangas?"
  ask "Do you like eating sopapillas?"
  puts "Just a few more questions . . "
  ask "Do you like horchata?"
  ask "Do you like eating flautas?"
  puts
  puts "DEBRIEFING"
  puts "Thank you for . . . . "
  puts
  puts wets_bed
